rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - rbx-19mode

notifications:
  irc: "irc.freenode.org#pry"
  recipients:
    - jrmair@gmail.com

branches:
  only:
    - master

matrix:
  include:
    - rvm: jruby
      env: JRUBY_OPTS=-X-C
  allow_failures:
    - rvm: jruby

#script: rake test --trace
#
#before_install:
#  - gem update --system
#  - gem --version
#  - gem install rake bacon
#  - rake gem
#  - gem install pkg/*.gem
